spring:
  application:
    name: how-about-us-backend

  jpa:
    open-in-view: false

  threads:
    virtual:
      enabled: true

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY}
    base-url: https://places.googleapis.com
    search-field-mask: places.id,places.displayName,places.formattedAddress,places.location,places.primaryType,places.rating,places.photos
    detail-field-mask: id,displayName,formattedAddress,location,primaryType,rating,nationalPhoneNumber,websiteUri,googleMapsUri,regularOpeningHours.weekdayDescriptions,photos.name

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
