#file: noinspection SpellCheckingInspection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      file:
        - compose.yaml
        - compose.dev.yaml

  jpa:
    hibernate:
      ddl-auto: create-drop

  mongodb:
    uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DB}?authSource=admin

cors:
  allowed-origins:
    - http://localhost:3000

springwolf:
  docket:
    servers:
      stomp-server:
        host: localhost:8080/ws
