spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      file:
        - compose.yaml
        - compose.dev.yaml
