#file: noinspection SpellCheckingInspection
name: Publish API Image

on:
  push:
    branches:
      - main
      - feature/ci-cd
    paths:
      - .github/workflows/deploy-compose.yml
      - src/**
      - build.gradle
      - settings.gradle
      - gradlew
      - gradlew.bat
      - gradle/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Make Version Tag
        id: version
        shell: bash
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Image tag: $SHORT_SHA"

      - name: Build and push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ./gradlew jib \
            -Djib.to.image="minbros/how-about-us-backend" \
            -Djib.to.tags=prod,${{ steps.version.outputs.tag }} \
            -Djib.to.auth.username="$DOCKERHUB_USERNAME" \
            -Djib.to.auth.password="$DOCKERHUB_TOKEN"
